### ISSUE TITLE
Failed to activate the atom-visual-studio-code-ui theme

### ISSUE THREAD

**Issue by c0deh4xor** [Zeioth/atom-visual-studio-code-ui#12]
[Enter steps to reproduce:]

1. Goto themes and selected Atom-Visual-Studio-Code UI Theme

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: [atom-visual-studio-code-ui](https://github.com/Zeioth/atom-visual-studio-code-ui) package 1.3.4

### Stack Trace

Failed to activate the atom-visual-studio-code-ui theme

```
At Unrecognised input. Possibly missing something in /Users/komplex/.atom/packages/atom-visual-studio-code-ui/styles/panes.less:72:0

LessError: Unrecognised input. Possibly missing something
at /Users/komplex/.atom/packages/atom-visual-studio-code-ui/styles/panes.less:72:0
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-visual-studio-code-ui 1.3.4 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
code-snapshot 0.1.0 
flex-tool-bar 2.1.0 
folded-code-preview 0.2.5 
git-plus 7.10.2 
Hydrogen 2.5.0 
mark-code-blocks 0.1.0 
styri-syntax 0.2.0 
term3 0.22.1 
tool-bar 1.1.7 
```

**Comment by Zeioth** [comment]
Fixed in master branch. Will be upstreamed soon. Cheers.
