### ISSUE TITLE
how config this toolbar?

### ISSUE THREAD

**Issue by worldcoding** [Zeioth/atom-visual-studio-code-ui#4]
like the image  in red line
![qq 20160416152155](https://cloud.githubusercontent.com/assets/13378254/14579727/2235a1a2-03e7-11e6-9845-f2443647f5ac.png)

**Comment by Zeioth** [comment]
In Atom, go to the config pressing "ctrl+," and then click on "Open config folder". In the file /atom-visual-studio-ui/styles.extra.less you'll find all styles from this theme. When you know what styles you want to modify, you can do it as described in the FAQ. Also, if you want to bring the toolbar to the front, i removed that feature due a an atom bug, please read #1 

```
  // ------------- Status bar -------------
  .status-bar{
    position: relative;
    font-size: 0.97em;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: #007ACC;
    span, a, a.inline-block{
      color: white;
    }
    .status-bar-right{
      color: white;
    }
  }
```

**Comment by worldcoding** [comment]
after config in your way,but not the same with example, the diffcult you can see the image.
![qq 20160417174315](https://cloud.githubusercontent.com/assets/13378254/14586229/1b406cbe-04c4-11e6-86e7-388018675b41.png)
