### ISSUE TITLE
Problem with atom 1.8

### ISSUE THREAD

**Issue by Cafnio** [Zeioth/atom-visual-studio-code-ui#5]
Hi there.

I've tried to install and it was all fine. The problem was when changing the theme in the options. It shows up the VS theme, I select it but it does nothing. after few seconds, it change back to atom dark one.

Anything I can do?

Thanks

**Comment by Zeioth** [comment]
I tested it in Atom 1.9.9 and it's working fine. Try reinstalling Atom. And after install the theme, re-open the editor. Also, ensure you are running the theme "atom-visual-studio-code-ui".
