### ISSUE TITLE
Deprecated selector in `atom-visual-studio-code-ui/index.less`

### ISSUE THREAD

**Issue by amandeepmittal** [Zeioth/atom-visual-studio-code-ui#6]
In `atom-visual-studio-code-ui/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini]::shadow .placeholder-text` => `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini].editor .placeholder-text`

* `atom-text-editor[mini] .selection .region,
atom-text-editor[mini]::shadow .selection .region` => `atom-text-editor[mini] .selection .region,
atom-text-editor[mini].editor .selection .region`

* `atom-text-editor[mini] .cursor,
atom-text-editor[mini]::shadow .cursor` => `atom-text-editor[mini] .cursor,
atom-text-editor[mini].editor .cursor`

* `atom-text-editor[mini].is-focused,
atom-text-editor[mini].is-focused::shadow` => `atom-text-editor[mini].is-focused,
atom-text-editor[mini].is-focused.editor`

* `atom-text-editor[mini].is-focused .selection .region,
atom-text-editor[mini].is-focused::shadow .selection .region` => `atom-text-editor[mini].is-focused .selection .region,
atom-text-editor[mini].is-focused.editor .selection .region`

* `.markdown-preview atom-text-editor::shadow .line.cursor-line` => `.markdown-preview atom-text-editor.editor .line.cursor-line`

* `.theme-atom-visual-studio-code-ui atom-text-editor .gutter,
.theme-atom-visual-studio-code-ui atom-text-editor::shadow .gutter` => `.theme-atom-visual-studio-code-ui atom-text-editor .gutter,
.theme-atom-visual-studio-code-ui atom-text-editor.editor .gutter`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by joaoeudes7** [comment]
Waiting....

**Comment by kkanedaa** [comment]
Please fix as its a beautiful theme :)

**Comment by Zeioth** [comment]
Fixed in master branch, will be upstreamed soon. Cheers.

**Comment by kkanedaa** [comment]
Have been waiting a year and 2 month for this theme :) Thanks for continuing it.
